# Generated by Django 6.0 on 2025-12-17 02:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0002_triageresult_lat_triageresult_lng_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('api_key', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='triageresult',
            name='ai_severity',
            field=models.CharField(blank=True, choices=[('RED', 'แดง'), ('YELLOW', 'เหลือง'), ('GREEN', 'เขียว')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='triageresult',
            name='nurse_severity',
            field=models.CharField(blank=True, choices=[('RED', 'แดง'), ('YELLOW', 'เหลือง'), ('GREEN', 'เขียว')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(default=django.utils.timezone.now)),
                ('bpm', models.IntegerField(blank=True, null=True)),
                ('o2sat', models.IntegerField(blank=True, null=True)),
                ('bt', models.FloatField(blank=True, null=True)),
                ('rr', models.IntegerField(blank=True, null=True)),
                ('sys_bp', models.IntegerField(blank=True, null=True)),
                ('dia_bp', models.IntegerField(blank=True, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='queues.device')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_logs', to='queues.visit')),
            ],
            options={
                'indexes': [models.Index(fields=['visit', 'ts'], name='queues_tele_visit_i_3f5ddc_idx')],
            },
        ),
    ]
