# Generated by Django 6.0 on 2025-12-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0003_device_alter_triageresult_ai_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
