# Generated by Django 6.0 on 2025-12-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O'), ('UNKNOWN', 'ไม่ทราบ')], default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='chronic_diseases',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'ชาย'), ('F', 'หญิง'), ('O', 'อื่นๆ')], default='UNKNOWN', max_length=1),
        ),
        migrations.AddField(
            model_name='patient',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='national_id',
            field=models.CharField(default=0, max_length=13, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hn',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
